### ISSUE TITLE
Could not find file blazor-intersection-observer.js

### ISSUE THREAD

**Issue by Michael-Anderlin** [ljbc1994/BlazorIntersectionObserver#24]
Hello,

At compilation I get the following error.
In the file system, the file blazor-intersection-observer.min.js exists at the right place.
Renaming it to blazor-intersection-observer.js suppress the error.

  Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68, 5): [MSB4018] The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.AggregateException: One or more errors occurred. (Could not find file '/XXXX/.nuget/packages/blazorintersectionobserver/2.0.0/staticwebassets/blazor-intersection-observer.js'.)
 ---> System.IO.FileNotFoundException: Could not find file '/XXXX/.nuget/packages/blazorintersectionobserver/2.0.0/staticwebassets/blazor-intersection-observer.js'.
File name: '/XXXX/.nuget/packages/blazorintersectionobserver/2.0.0/staticwebassets/blazor-intersection-observer.js'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[...]
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.GenerateAssetManifest(Stream stream)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

 - OS: OSx

**Comment by ljbc1994** [comment]
Hi Michael,

This looks to be an issue with `ServiceWorkerAssetsManifest`. I'll have a look to see what's happening with that.

Thanks

**Comment by Michael-Anderlin** [comment]
One more information, when the web assembly app runs, it complains about missing blazor-intersection-observer.min.js.
It works if I have both blazor-intersection-observer.js and blazor-intersection-observer.min.js... :)

**Comment by ljbc1994** [comment]
It could have been because of changing to `min.js`, I've updated the csproj to reflect this so hopefully this resolves the issue in 
version `2.0.2`.

**Comment by Michael-Anderlin** [comment]
Tx Louie,

Upgraded nuget to 2.0.2 but still complaining at build. Still looking for the unmagnified file :(

  Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68, 5): [MSB4018] The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.AggregateException: One or more errors occurred. (Could not find file '/XXX/.nuget/packages/blazorintersectionobserver/**2.0.2**/staticwebassets/blazor-intersection-observer.js'.)
 ---> System.IO.FileNotFoundException: Could not find file

**Comment by ljbc1994** [comment]
Hmm okay, that's strange. Thanks for letting me know, when I have time I'll see what's happening with that.

**Comment by Michael-Anderlin** [comment]
As a side effect, I'm not able to deploy on Azure because I cannot duplicate the file upon deployment...
Is it possible to quickly release a version with the two files ?

Tx

**Comment by ljbc1994** [comment]
Of course, I've just deployed `2.0.3` which contains the unminifed file. Hope that helps in the meantime.

**Comment by Michael-Anderlin** [comment]
Many thanks !!!
