### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'x')

### ISSUE THREAD

**Issue by hanj73** [ljbc1994/BlazorIntersectionObserver#49]
**Describe the bug**
TypeError exception occurs when we navigate back while observing a blazor component.

**To Reproduce**
1. Go to a page with a blazor component that is being observed.
2. Navigate back using JSRuntime.InvokeVoidAsync("history.go", "-1");
3. See error

**Expected behavior**
No exception when navigating back

**Screenshots**
![image](https://user-images.githubusercontent.com/48692950/221982420-ba724b7f-1ab9-4292-a13a-29216ce4ce4e.png)
Uncaught TypeError TypeError: Cannot read properties of null (reading 'x')
    at t (C:\Users\\######\\.nuget\packages\blazorintersectionobserver\3.1.0\staticwebassets\blazor-intersection-observer.min.js:1:255)
    at <anonymous> (C:\Users\\######\\.nuget\packages\blazorintersectionobserver\3.1.0\staticwebassets\blazor-intersection-observer.min.js:1:528)
    at <anonymous> (C:\Users\\######\\.nuget\packages\blazorintersectionobserver\3.1.0\staticwebassets\blazor-intersection-observer.min.js:1:545)
    at <anonymous> (C:\Users\\######\\.nuget\packages\blazorintersectionobserver\3.1.0\staticwebassets\blazor-intersection-observer.min.js:1:210)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome/Edge/Firefox]
 - Version [110.0.5481.177/110.0.1587.50/110.0]

**Additional context**
I can't reproduce this issue on my machine, but it happens every time on my colleague's machine. We'll provide an update on this when we have more details.

**Comment by harry-flw** [comment]
Hello.
I have the same issue.
I have used https://github.com/stavroskasidis/BlazorDialog . And every time when I click to open "Modal Dialog" the same TypeError exception occurs.

**Comment by harry-flw** [comment]
Any news?

**Comment by alexh-compyl** [comment]
I'm also running into this issue suddenly - I'm doing some custom JS work with some drag and drop behavior and this just now showed up. Assuming this is a dead issue?

**Comment by harry-flw** [comment]
Hello.
Is it possible to release the new NuGet-packet with this fix?
Thank you in advance
